"""init

Revision ID: 3987c94ccd90
Revises: 
Create Date: 2026-04-30 19:06:10.439695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3987c94ccd90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_24_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_4_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_30_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('reminder_30_sent')
        batch_op.drop_column('reminder_4_sent')
        batch_op.drop_column('reminder_24_sent')

    # ### end Alembic commands ###
